#!/usr/bin/env php

<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Aggrcows\AggrcowsCommand;

$app = new Application();
$command = new AggrcowsCommand();
$app->add($command);
$app->setDefaultCommand($command->getName(), true);
$app->run();
